all:
  vars:
    ansible_ssh_private_key_file: ../sshkeys/iac-for-everyone
    ansible_user: root

load-balancer:
  vars:
  hosts:
    load-balancer:
      ansible_host: 157.230.81.188
      haproxy_width_stats: True
      haproxy_with_auth: False
      haproxy_user: user
      haproxy_password: password


# Nginx Servers
web-servers:
  hosts:
    nginx-01:
      ansible_host: 157.230.83.214
    nginx-02:
       ansible_host: 157.230.7.221
    nginx-03:
      ansible_host: 157.230.11.19
